=== iwe7/iwe7-json-schema/src/app/widgets/schema/widget.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "debug": {
      "type": "boolean"
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string",
      "title": "名称"
    },
    "inputs": {
      "$ref": "./inputs.json"
    },
    "outputs": {
      "$ref": "./outputs.json"
    },
    "events": {
      "type": "object",
      "title": "方法"
    },
    "className": {
      "type": "object",
      "title": "样式类"
    },
    "style": {
      "type": "object",
      "title": "内联样式"
    },
    "contents": {
      "type": "object",
      "title": "内容"
    },
    "isLazy": {
      "type": "boolean",
      "default": true,
      "title": "是否懒加载"
    },
    "script": {
      "type": "string",
      "title": "地址"
    },
    "selector": {
      "type": "string",
      "title": "选择符"
    },
    "wechat": {
      "type": "string",
      "title": "微信选择符"
    }
  },
  "required": [
    "name", "inputs", "isLazy", "script", "selector"
  ]
}

=== iwe7/iwe7-json-schema/src/app/widgets/widget-text/widget-text.default.json
{
  "$schema": "./widget-text.schema.json",
  "name": "文本",
  "debug": true,
  "id": "id01",
  "inputs": {
    "decode": false,
    "selectable": false,
    "space": "nbsp"
  },
  "outputs": {
    "iClick": {
      "method": "changeText",
      "params": {
        "text": "我是一个新的文本"
      },
      "target": "id01"
    }
  },
  "isLazy": true,
  "script": "widget-text",
  "selector": "widget-text",
  "wechat": "text",
  "className": {},
  "style": {},
  "contents": {
    "text": "我是一段文本"
  }
}

=== iwe7/iwe7-json-schema/src/json/widgets/widget-text.default.json
{
  "$schema": "./widget-text.schema.json",
  "name": "文本",
  "debug": true,
  "id": "id01",
  "inputs": {
    "decode": false
  },
  "outputs": {
    "iClick": {
      "method": "changeText",
      "params": {
        "text": "我是一个新的文本"
      },
      "target": "id01"
    }
  },
  "isLazy": true,
  "script": "widget-text",
  "selector": "widget-text",
  "wechat": "text",
  "className": {},
  "style": {},
  "contents": {
    "text": "我 是 一 段 文 本"
  }
}
